"""add expected_salary to candidate profiles

Revision ID: 35b74f41925d
Revises: 2003c742940d
Create Date: 2026-09-23 06:08:35.506669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b74f41925d'
down_revision: Union[str, None] = '2003c742940d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('expected_salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'expected_salary')
    # ### end Alembic commands ###
